repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmDefaults:
  wait: true
  timeout: 600
  atomic: true
  createNamespace: true

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: "39.0.7"
    values:
      - values/traefik.yaml

  - name: postgres-projects
    namespace: apps-deployer
    chart: bitnami/postgresql
    version: "18.5.16"
    values:
      - values/postgresql-projects.yaml
    set:
      - name: auth.database
        value: projects_db

  - name: postgres-deployments
    namespace: apps-deployer
    chart: bitnami/postgresql
    version: "18.5.16"
    values:
      - values/postgresql-deployments.yaml
    set:
      - name: auth.database
        value: deployments_db

  - name: postgres-auth
    namespace: apps-deployer
    chart: bitnami/postgresql
    version: "18.5.16"
    values:
      - values/postgresql-auth.yaml
    set:
      - name: auth.database
        value: auth_db

  - name: celery-broker
    namespace: apps-deployer
    chart: bitnami/redis
    version: "25.3.10"
    values:
      - values/redis.yaml
